import Image from 'next/image';

/**
 * The Jasora badge, matching the app icon and the browser tab.
 *
 * The whole badge rather than the pin on its own: the pin is orange on navy,
 * and lifted off its ground it strands against the admin's light theme.
 * Carrying its own ground means one asset works on both themes — which is also
 * why this no longer inherits currentColor the way the old flat mark did.
 *
 * Regenerated by scripts/generate-icons.mjs; do not hand-edit the PNG.
 */
export function JasoraMark({ className }: { className?: string }) {
  return (
    <Image
      src="/jasora-mark.png"
      alt=""
      aria-hidden
      width={256}
      height={256}
      // Rendered at 24–40px, so the 256px source is well past retina and never
      // needs the optimiser.
      unoptimized
      className={className}
    />
  );
}
